// Blue Pencil Marginalia: tags words with a part of speech (compromise) and flags mechanical
// signals about rhythm and structure. Signals, not verdicts: nothing here rewrites
// anything. Emits CSS classes only; styles.css says how each looks, the side panel
// says what shows. main.js is generated by build.sh (compromise + rules.js + this file).
const { Plugin, ItemView, Setting, Notice, MarkdownView, debounce } = require("obsidian");
const { ViewPlugin, Decoration } = require("@codemirror/view");
const { StateEffect } = require("@codemirror/state");

const LONG_WORDS = 25;      // sentence marked "long": the GOV.UK plain-language ceiling
const VERY_LONG_WORDS = 45; // sentence marked "very long"
const OPENER_RUN = 3;       // same first word, this many sentences in a row
const EVEN_RUN = 3;         // sentences of near-equal length in a row (within 30%, 6+ words)
const ZIGZAG_RUN = 6;       // sentences alternating long/short...
const ZIGZAG_DIFF = 8;      // ...each step at least this many words
const SHORT_PARA_WORDS = 15; // a one-sentence paragraph this short counts as a "punch"
const METRO_RUN = 4;        // punch paragraphs at near-regular spacing
const WPM = 238;
const THIRD = new Set(["he", "she", "him", "her", "his", "hers", "himself", "herself"]);
const SECOND = new Set(["you", "your", "yours", "yourself"]);
const SHORT_SENT = 5;       // a "short" sentence, in words
const BARE_SPEECH = 5;      // words outside the quotes that still count as bare speech
const STACC_RUN = 3;        // short sentences in a row
const PARAOPEN_RUN = 3;     // paragraphs opening on the same word
const TAGRUN = 4;           // dialogue paragraphs in a row each carrying a said/asked tag
const TALK_RUN = 6;         // dialogue paragraphs in a row with nothing but the speech
const RADAR_WINDOW = 25;   // words
const RADAR_MIN = 6;       // letters

// ---------- text prep ----------

// Same-length blanking so offsets still map back to the document.
function maskLine(text) {
  const blank = (m) => " ".repeat(m.length);
  return text
    .replace(/`[^`]*`/g, blank)
    .replace(/\]\([^)]*\)/g, blank)
    .replace(/https?:\/\/\S+/g, blank)
    .replace(/\[\[([^\]|]*\|)?/g, blank).replace(/\]\]/g, blank)
    .replace(/%%[^%]*%%/g, blank)
    .replace(/\$[^$\n]+\$/g, blank)
    .replace(/\[\^[^\]]+\]/g, blank)
    .replace(/^\s*(#{1,6}\s|(?:>\s?)+|[-*+]\s|\d+[.)]\s)(\[.\]\s)?(\[![^\]]+\][+-]?\s?)?/, blank)
    .replace(/[*~=]+|(?<![\p{L}\p{N}])_+|_+(?![\p{L}\p{N}])|[[\]]/gu, blank)
    .replace(/<[^>]+>/g, blank);
}

function wordCount(s) { return (s.match(/[\p{L}\p{N}][\p{L}\p{N}'’-]*/gu) || []).length; }

function syllables(word) {
  const w = word.toLowerCase().replace(/[^a-z]/g, "");
  if (!w) return 1;
  if (w.length <= 3) return 1;
  const m = w.replace(/(?:[^laeiouy]es|ed|[^laeiouy]e)$/, "").replace(/^y/, "").match(/[aeiouy]{1,2}/g);
  return m ? m.length : 1;
}

// Offset just past a closing frontmatter fence, or 0 when the note has none (an unclosed "---" is just text).
function frontmatterEnd(text) {
  if (!/^---[ \t]*\n/.test(text)) return 0;
  const re = /\n(?:---|\.\.\.)[ \t]*(?:\n|$)/g;
  re.lastIndex = 3;
  const m = re.exec(text);
  return m ? m.index + m[0].length : 0;
}

// Frontmatter and fenced code, as a set of 0-based line indexes.
function skippedLines(lines, fmEnd) {
  const skip = new Set();
  let fence = null;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].from < fmEnd) { skip.add(i); continue; }
    const f = /^\s*(```+|~~~+)/.exec(lines[i].text);
    if (fence) { skip.add(i); if (f && f[1][0] === fence[0] && f[1].length >= fence.length) fence = null; continue; }
    if (f) { fence = f[1]; skip.add(i); }
  }
  return skip;
}

// Prose blocks (consecutive plain lines) and single-line non-prose blocks (headings, lists, quotes, tables).
function toBlocks(text) {
  const lines = [];
  let off = 0;
  for (const t of text.split("\n")) { lines.push({ from: off, text: t }); off += t.length + 1; }
  const skip = skippedLines(lines, frontmatterEnd(text));
  const blocks = [];
  let cur = null;
  const close = () => { if (cur) { blocks.push(cur); cur = null; } };
  lines.forEach((l, i) => {
    if (skip.has(i) || !l.text.trim() || /^\s*([-*_]\s*){3,}$/.test(l.text) || /^\s*!\[/.test(l.text)) return close();
    const masked = maskLine(l.text);
    if (/^\s{0,3}#{1,6}\s|^\s*([-*+]|\d+[.)])\s|^\s*>|^\s*\|/.test(l.text)) {
      close();
      blocks.push({ from: l.from, text: masked, prose: false, kind: /^\s{0,3}#{1,6}\s/.test(l.text) ? "heading" : /^\s*([-*+]|\d+[.)])\s/.test(l.text) ? "list" : "other" });
    } else if (cur) {
      cur.text += "\n" + masked;
    } else {
      cur = { from: l.from, text: masked, prose: true };
    }
  });
  close();
  return blocks;
}

// ---------- per-block analysis (cached) ----------

function bucket(tags) {
  if (tags.includes("Adverb")) return "adv";
  if (tags.includes("Adjective")) return "adj";
  if (tags.includes("Verb") || tags.includes("Auxiliary") || tags.includes("Modal") || tags.includes("Copula")) return "verb";
  if (tags.includes("Conjunction") || tags.includes("Preposition") || tags.includes("Connector")) return "conj";
  if (tags.includes("Noun") || tags.includes("Pronoun")) return "noun";
  return null;
}

function stemOf(lw) {
  const rw = lw.replace(/[^a-z']/g, "");
  if (rw.length < 4 || RADAR_STOP.has(rw)) return null;
  const st = rw.replace(/(ing|ed|es|s)$/, "");
  return st.length >= 4 ? st : rw;
}

function analyzeBlock(nlp, text, prose) {
  const hits = [], sents = [], toks = [];
  let nWords = 0, nAdv = 0, syl = 0, nTok = 0, nPast = 0, nThird = 0, nSecond = 0, nAdj = 0, nComplex = 0, nContr = 0, nSpec = 0;
  const lws = [], blockStems = new Set(), tagPos = [];
  const add = (from, to, cls) => { if (to > from) hits.push({ from, to, cls }); };
  const spans = [];
  DIALOGUE.lastIndex = 0;
  let md;
  while ((md = DIALOGUE.exec(text))) { if (md[0].length < 2) { DIALOGUE.lastIndex++; continue; } spans.push([md.index, md.index + md[0].length]); add(md.index, md.index + md[0].length, "sl-dialogue"); }
  const inSpan = (i) => spans.some((sp) => i >= sp[0] && i < sp[1]);
  for (const s of nlp(text).json({ offset: true })) {
    const terms = [];
    for (const t of s.terms) {
      const from = t.offset.start, to = from + t.offset.length;
      if (to > from && /[\p{L}\p{N}]/u.test(text.slice(from, to))) terms.push({ from, to, tags: t.tags, lw: t.text.toLowerCase() });
    }
    if (!terms.length) continue;
    const sFrom = terms[0].from;
    let sTo = terms[terms.length - 1].to;
    while (/[.!?…"”'’)\]]/.test(text[sTo] || "")) sTo++;
    const stext = text.slice(sFrom, sTo);
    const words = wordCount(stext);
    const stems = [], openStems = [];
    const t0 = terms[0], t1 = terms[1];
    if (VAGUE.has(t0.lw) && !(/^(this|that|these|those)$/.test(t0.lw) && t1 && /Noun|Adjective|Value|Cardinal/.test(t1.tags.join(" ")))) add(t0.from, t0.to, "sl-vague");

    // syntax and word-level
    let run = null, passive = false;
    terms.forEach((t, i) => {
      const stm = stemOf(t.lw);
      if (stm && t.lw.replace(/[^a-z']/g, "").length >= RADAR_MIN) toks.push({ i: nTok + i, key: stm, from: t.from, to: t.to });
      const b = bucket(t.tags);
      if (b) add(t.from, t.to, "sl-" + b);
      if (b === "adv") nAdv++;
      if (b === "adj") nAdj++;
      lws.push(t.lw);
      if (stm) { stems.push(stm); blockStems.add(stm); if (i < 4) openStems.push(stm); }
      if (!t.tags.includes("ProperNoun") && syllables(t.lw) >= 3) nComplex++;
      const raw = text.slice(t.from, t.to);
      const isSpec = !/^i['\u2019]|^i$/.test(t.lw) && (t.tags.some((g) => SPEC_TAGS.has(g)) && (!t.tags.includes("Acronym") || /^[A-Z]{2,}$/.test(raw)) || (/\d/.test(raw) && t.tags.some((g) => g === "Value" || g === "Cardinal" || g === "Money" || g === "Percent")));
      if (isSpec) { nSpec++; add(t.from, t.to, "sl-spec"); }
      if (NOM_RE.test(t.lw) && t.lw.length >= 7 && !NOM_STOP.has(t.lw) && !/^[A-Z]/.test(text[t.from])) add(t.from, t.to, "sl-nom");
      if (t.tags.includes("PastTense")) nPast++;
      if (THIRD.has(t.lw)) nThird++; else if (SECOND.has(t.lw)) nSecond++;
      if (FILLER.has(t.lw)) add(t.from, t.to, "sl-filler");
      const prev = terms[i - 1];
      if (prev && prev.lw === t.lw && /^[a-z']+$/.test(t.lw) && t.lw !== "had" && t.lw !== "that" && !text.slice(prev.to, t.from).trim()) add(prev.from, t.to, "sl-repeat");
      if (t.lw === "which" && prev && /,\s*$/.test(text.slice(prev.to, t.from))) add(t.from, t.to, "sl-which");
      if (t.tags.includes("Passive") || (run && t.tags.includes("Auxiliary"))) {
        run = run || { from: t.from, n: 0 };
        run.to = t.to; run.n++;
      } else if (run) { if (run.n) { add(run.from, run.to, "sl-passive"); passive = true; } run = null; }
    });
    if (run && run.n) { add(run.from, run.to, "sl-passive"); passive = true; }
    FILLER_PHRASES.lastIndex = 0;
    let m;
    while ((m = FILLER_PHRASES.exec(stext))) add(sFrom + m.index, sFrom + m.index + m[0].length, "sl-filler");

    // triplets: a, b, and c with three words of the same kind
    for (let i = 0; i + 3 < terms.length; i++) {
      const [a, b, c, d] = [terms[i], terms[i + 1], terms[i + 2], terms[i + 3]];
      const ba = bucket(a.tags);
      if (!ba || ba === "conj" || ba !== bucket(b.tags) || ba !== bucket(d.tags)) continue;
      if ((c.lw !== "and" && c.lw !== "or")) continue;
      if (/^\s*,\s*$/.test(text.slice(a.to, b.from)) && /^\s*,?\s*$/.test(text.slice(b.to, c.from)) && /^\s+$/.test(text.slice(c.to, d.from)))
        add(a.from, d.to, "sl-triplet");
    }

    // phrase rules, one sentence at a time
    for (const cls in PHRASE_RULES) for (const re of PHRASE_RULES[cls]) {
      re.lastIndex = 0;
      while ((m = re.exec(stext))) {
        if (!m[0]) { re.lastIndex++; continue; }
        if (cls === "sl-tagadv" && m[1]) add(sFrom + m.index + m[0].length - m[1].length, sFrom + m.index + m[0].length, cls);
        else add(sFrom + m.index, sFrom + m.index + m[0].length, cls);
      }
    }
    CONTRACTION.lastIndex = 0;
    nContr += (stext.match(CONTRACTION) || []).length;
    // fancy dialogue tags: a speech verb next to a quote mark
    FANCY_TAGS.lastIndex = 0;
    while ((m = FANCY_TAGS.exec(stext))) {
      const ctx = text.slice(Math.max(0, sFrom + m.index - 14), sFrom + m.index + m[0].length + 14);
      if (/["\u201c\u201d]/.test(ctx)) add(sFrom + m.index, sFrom + m.index + m[0].length, "sl-tagfancy");
    }
    // rhetorical question outside dialogue
    if (/\?["\u201d\u2019')\]]*$/.test(stext) && !inSpan(sFrom + stext.lastIndexOf("?"))) add(sFrom, sTo, "sl-rhetq");
    // stacked modifiers: 2+ adverbs or 3+ adjectives in a row
    for (let i = 0; i < terms.length;) {
      const bk = bucket(terms[i].tags);
      if (bk !== "adv" && bk !== "adj") { i++; continue; }
      let j = i;
      while (j + 1 < terms.length) {
        const n1 = terms[j + 1];
        if (bucket(n1.tags) === bk && /^[\s,]*$/.test(text.slice(terms[j].to, n1.from))) j++;
        else if ((n1.lw === "and" || n1.lw === "or") && terms[j + 2] && bucket(terms[j + 2].tags) === bk) j += 2;
        else break;
      }
      const cnt = terms.slice(i, j + 1).filter((t) => bucket(t.tags) === bk).length;
      if (cnt >= (bk === "adv" ? 2 : 3)) add(terms[i].from, terms[j].to, "sl-stack");
      i = j + 1;
    }
    if (words <= 8 && /^not\b/i.test(stext)) add(sFrom, sTo, "sl-negpar");

    if (prose) {
      if (words >= VERY_LONG_WORDS) add(sFrom, sTo, "sl-vlong");
      else if (words >= LONG_WORDS) add(sFrom, sTo, "sl-long");
    }
    nTok += terms.length;
    nWords += words;
    syl += (stext.match(/[A-Za-z]+/g) || []).reduce((n, w) => n + syllables(w), 0);
    sents.push({ from: sFrom, to: sTo, words, text: stext, first: terms[0].lw, firstTo: terms[0].to, passive, stems: [...new Set(stems)], open: openStems, openTo: terms[Math.min(3, terms.length - 1)].to, link: LINKERS.has(terms[0].lw) || bucket(terms[0].tags) === "adv" });
  }
  PUNCT.lastIndex = 0;
  let m2;
  while ((m2 = PUNCT.exec(text))) {
    add(m2.index, m2.index + 1, "sl-punct");
    if (m2[0] === ";" && inSpan(m2.index)) add(m2.index, m2.index + 1, "sl-dlgsemi");
  }
  NEUTRAL_TAG.lastIndex = 0;
  let mt;
  while ((mt = NEUTRAL_TAG.exec(text))) if (!inSpan(mt.index)) tagPos.push([mt.index, mt.index + mt[0].length]);

  if (prose && sents.length >= 2) { // aphoristic beat-closer candidate
    const last = sents[sents.length - 1], prev = sents[sents.length - 2];
    if (last.words <= 8 && prev.words >= 10 && /^(?:and )?(?:that|this|it)(?:['’]s| was| is| were)\b/i.test(last.text)) add(last.from, last.to, "sl-closer");
  }
  if (prose && sents.length) { // wrap-up tail: a closing participial or "a reminder of" phrase
    const last = sents[sents.length - 1];
    const wt = /,\s+((?:(?!(?:(?:some|no|any|every)?thing|morning|evening|king|string|spring|ring|wing|ceiling|darling|sibling|swing|bring|sing|cling)\b)[a-z]+ing|a (?:reminder|testament|symbol|sign|promise)|proof|evidence)\b[^,.;!?]*)[.!?…"”']*$/i.exec(last.text);
    if (wt && wordCount(wt[1]) >= 3) add(last.from + wt.index + wt[0].indexOf(wt[1]), last.to, "sl-tail");
  }
  const dlg = (text.match(/["“][^"”]*["”]/g) || []).reduce((n, q) => n + wordCount(q), 0);
  const outside = spans.reduce((t, sp) => t.slice(0, sp[0]) + " ".repeat(sp[1] - sp[0]) + t.slice(sp[1]), text);
  return { hits, sents, toks, nTok, nWords, nAdv, nPast, nThird, nSecond, nAdj, nComplex, nContr, nSpec, lws, stems: [...blockStems], tagPos, outsideWords: wordCount(outside), syl, dlg, dlgPara: /^\s*["“]/.test(text) };
}

// ---------- whole-note analysis ----------

// ---------- pacing: how unevenly the prose is paced, from the series of sentence lengths ----------
const meanOf = (a) => a.reduce((x, y) => x + y, 0) / a.length;
const sdOf = (a) => { const m = meanOf(a); return Math.sqrt(meanOf(a.map((x) => (x - m) ** 2))); };

// Lumpiness as tsfeatures defines it (variance of the variances over tiled windows), made scale-free
// by dividing by the mean window variance. Even pacing gives a low value, bursts of wildness a high one.
function lumpiness(x, win = 10) {
  const v = [];
  for (let i = 0; i + win <= x.length; i += win) v.push(sdOf(x.slice(i, i + win)) ** 2);
  if (v.length < 3 || !meanOf(v)) return null;
  return sdOf(v) / meanOf(v);
}

// Detrended fluctuation analysis exponent of the series (the Hurst-style measure used on sentence
// lengths in literary texts). Near 0.5 is random pacing, above 0.5 is persistent (long stretches stay
// long or short), below 0.5 is anti-persistent (a steady long/short alternation).
function dfaExponent(x) {
  const N = x.length;
  if (N < 40) return null;
  const mu = meanOf(x);
  const y = [];
  let c = 0;
  for (const v of x) { c += v - mu; y.push(c); }
  const pts = [];
  for (let n = 4; n <= Math.floor(N / 4); n = Math.ceil(n * 1.35)) {
    const k = Math.floor(N / n);
    let F = 0;
    for (let b = 0; b < k; b++) {
      const seg = y.slice(b * n, (b + 1) * n), tm = (n - 1) / 2, sm = meanOf(seg);
      let num = 0, den = 0;
      for (let i = 0; i < n; i++) { num += (i - tm) * (seg[i] - sm); den += (i - tm) ** 2; }
      const sl = num / den, ic = sm - sl * tm;
      for (let i = 0; i < n; i++) F += (seg[i] - (sl * i + ic)) ** 2;
    }
    if (F > 0) pts.push([Math.log(n), Math.log(Math.sqrt(F / (k * n)))]);
  }
  if (pts.length < 4) return null;
  const xm = meanOf(pts.map((p) => p[0])), ym = meanOf(pts.map((p) => p[1]));
  let nu = 0, de = 0;
  for (const [a, b] of pts) { nu += (a - xm) * (b - ym); de += (a - xm) ** 2; }
  return nu / de;
}

// Moving-average type-token ratio: vocabulary diversity that doesn't depend on length.
function mattr(ws, win = 50) {
  if (!ws.length) return 0;
  if (ws.length <= win) return new Set(ws).size / ws.length;
  const c = new Map();
  let uniq = 0, sum = 0;
  for (let i = 0; i < ws.length; i++) {
    c.set(ws[i], (c.get(ws[i]) || 0) + 1); if (c.get(ws[i]) === 1) uniq++;
    if (i >= win) { const o = ws[i - win]; c.set(o, c.get(o) - 1); if (c.get(o) === 0) uniq--; }
    if (i >= win - 1) sum += uniq / win;
  }
  return sum / (ws.length - win + 1);
}

const blockCache = new Map();
const CACHE_CHARS = 2e6; // keys are whole paragraphs; this caps what the cache holds
let cacheChars = 0;
let memo = { text: null, result: null };

function analyzeDoc(nlp, text) {
  if (memo.text === text) return memo.result;
  const hits = [], sents = [], paras = [], allLws = [], tagRuns = [];
  let words = 0, adv = 0, syl = 0, dlgWords = 0, dlgParas = 0, tokBase = 0, past = 0, third = 0, second = 0, adj = 0, complex = 0, contr = 0, spec = 0, headings = 0, lists = 0;
  const radar = [];
  toBlocks(text).forEach((b, bi) => {
    const key = (b.prose ? "p|" : "n|") + b.text;
    let r = blockCache.get(key);
    if (!r) {
      r = analyzeBlock(nlp, b.text, b.prose);
      if (cacheChars > CACHE_CHARS) { blockCache.clear(); cacheChars = 0; }
      blockCache.set(key, r);
      cacheChars += key.length;
    }
    for (const h of r.hits) hits.push({ from: b.from + h.from, to: b.from + h.to, cls: h.cls, b: bi });
    if (!b.prose) { if (b.kind === "heading") headings++; else if (b.kind === "list") lists++; return; }
    for (const t of r.toks) radar.push({ i: tokBase + t.i, key: t.key, from: b.from + t.from, to: b.from + t.to, b: bi });
    tokBase += r.nTok;
    if (!r.sents.length) return;
    const para = { b: bi, from: b.from, to: b.from + b.text.length, words: r.nWords, sents: r.sents.length, firstSent: sents.length, dlg: r.dlgPara, outside: r.outsideWords, tags: r.tagPos.map((t) => [b.from + t[0], b.from + t[1]]), stems: new Set(r.stems) };
    paras.push(para);
    for (const s of r.sents) sents.push({ from: b.from + s.from, to: b.from + s.to, words: s.words, first: s.first, firstTo: b.from + s.firstTo, passive: s.passive, b: bi, p: paras.length - 1, stems: s.stems, open: s.open, openTo: b.from + s.openTo, link: s.link });
    for (const w of r.lws) allLws.push(w);
    adj += r.nAdj; complex += r.nComplex; contr += r.nContr; spec += r.nSpec;
    past += r.nPast; third += r.nThird; second += r.nSecond;
    words += r.nWords; adv += r.nAdv; syl += r.syl; dlgWords += r.dlg; dlgParas += r.dlgPara ? 1 : 0;
  });
  const flag = (from, to, cls, b) => hits.push({ from, to, cls, b });

  // repetition radar: a content word recurring within RADAR_WINDOW words
  const seen = new Map();
  for (const t of radar) {
    const p = seen.get(t.key);
    if (p && t.i - p.i <= RADAR_WINDOW) {
      if (!p.flagged) flag(p.from, p.to, "sl-radar", p.b);
      flag(t.from, t.to, "sl-radar", t.b);
      seen.set(t.key, { ...t, flagged: true });
    } else seen.set(t.key, { ...t, flagged: false });
  }
  // same word opening sentences in a row, within a paragraph
  for (let i = 0; i < sents.length;) {
    let j = i;
    while (j + 1 < sents.length && sents[j + 1].b === sents[i].b && sents[j + 1].first === sents[i].first) j++;
    if (j - i + 1 >= OPENER_RUN) for (let k = i; k <= j; k++) flag(sents[k].from, sents[k].firstTo, "sl-opener", sents[k].b);
    i = j + 1;
  }
  // near-equal-length runs, within a paragraph
  let longestEven = 0;
  for (let i = 0; i < sents.length;) {
    let j = i, lo = sents[i].words, hi = lo;
    while (j + 1 < sents.length && sents[j + 1].b === sents[i].b) {
      const w = sents[j + 1].words, nlo = Math.min(lo, w), nhi = Math.max(hi, w);
      if (nlo < 6 || nhi / nlo > 1.3) break;
      lo = nlo; hi = nhi; j++;
    }
    if (j - i + 1 >= EVEN_RUN && lo >= 6) {
      longestEven = Math.max(longestEven, j - i + 1);
      for (let k = i; k <= j; k++) flag(sents[k].from, sents[k].to, "sl-even", sents[k].b);
      i = j + 1;
    } else i++;
  }
  // alternating long/short across the note
  let zigzags = 0;
  for (let i = 0; i + 1 < sents.length;) {
    let j = i, sign = 0;
    while (j + 1 < sents.length) {
      const d = sents[j + 1].words - sents[j].words;
      if (Math.abs(d) < ZIGZAG_DIFF || (sign && Math.sign(d) === sign)) break;
      sign = Math.sign(d); j++;
    }
    if (j - i + 1 >= ZIGZAG_RUN) { zigzags++; for (let k = i; k <= j; k++) flag(sents[k].from, sents[k].to, "sl-zigzag", sents[k].b); i = j + 1; }
    else i = Math.max(j, i + 1);
  }
  // punch paragraphs at near-regular spacing
  const punch = paras.map((p, i) => (p.sents === 1 && p.words <= SHORT_PARA_WORDS ? i : -1)).filter((i) => i >= 0);
  for (let i = 0; i < punch.length;) {
    let j = i, gap = null;
    while (j + 1 < punch.length) {
      const g = punch[j + 1] - punch[j];
      if (g < 2 || (gap !== null && Math.abs(g - gap) > 1)) break;
      gap = g; j++;
    }
    if (j - i + 1 >= METRO_RUN) { for (let k = i; k <= j; k++) flag(paras[punch[k]].from, paras[punch[k]].to, "sl-metro", paras[punch[k]].b); i = j + 1; }
    else i++;
  }

  // staccato: 3+ very short sentences in a row, within a paragraph
  for (let i = 0; i < sents.length;) {
    let j = i;
    if (sents[i].words > SHORT_SENT) { i++; continue; }
    while (j + 1 < sents.length && sents[j + 1].b === sents[i].b && sents[j + 1].words <= SHORT_SENT) j++;
    if (j - i + 1 >= STACC_RUN) for (let k = i; k <= j; k++) flag(sents[k].from, sents[k].to, "sl-stacc", sents[k].b);
    i = j + 1;
  }
  // paragraphs opening on the same word, 3+ in a row
  for (let i = 0; i < paras.length;) {
    const w0 = sents[paras[i].firstSent] && sents[paras[i].firstSent].first;
    let j = i;
    while (w0 && j + 1 < paras.length && sents[paras[j + 1].firstSent] && sents[paras[j + 1].firstSent].first === w0) j++;
    if (j - i + 1 >= PARAOPEN_RUN) for (let k = i; k <= j; k++) { const s0 = sents[paras[k].firstSent]; flag(s0.from, s0.firstTo, "sl-paraopen", paras[k].b); }
    i = j + 1;
  }
  // topic jump: a sentence whose opening links back to nothing earlier in its paragraph
  const pre = (x) => x.slice(0, 5);
  for (let i = 1, seen = new Set((sents[0] ? sents[0].stems : []).map(pre)); i < sents.length; i++) {
    const s0 = sents[i];
    if (s0.b !== sents[i - 1].b) { seen = new Set(s0.stems.map(pre)); continue; }
    if (s0.words >= 8 && sents[i - 1].words >= 5 && !s0.link && s0.open.length && seen.size >= 4 && !s0.open.some((x) => seen.has(pre(x)))) flag(s0.from, s0.openTo, "sl-jump", s0.b);
    for (const x of s0.stems) seen.add(pre(x));
  }
  // dialogue runs: attribution on every line, and talking heads
  for (let i = 0; i < paras.length;) {
    if (!paras[i].dlg) { i++; continue; }
    let j = i;
    while (j + 1 < paras.length && paras[j + 1].dlg && paras[j + 1].b === paras[j].b + 1) j++;
    const run = paras.slice(i, j + 1);
    let k = 0;
    while (k < run.length) { // neutral tag on every paragraph, 4+ in a row
      if (!run[k].tags.length) { k++; continue; }
      let e = k;
      while (e + 1 < run.length && run[e + 1].tags.length) e++;
      if (e - k + 1 >= TAGRUN) for (let q = k; q <= e; q++) for (const t of run[q].tags) flag(t[0], t[1], "sl-tagrun", run[q].b);
      k = e + 1;
    }
    k = 0;
    while (k < run.length) { // pure speech, nothing but a tag, 6+ in a row
      if (run[k].outside > BARE_SPEECH) { k++; continue; }
      let e = k;
      while (e + 1 < run.length && run[e + 1].outside <= BARE_SPEECH) e++;
      if (e - k + 1 >= TALK_RUN) for (let q = k; q <= e; q++) flag(run[q].from, run[q].to, "sl-talk", run[q].b);
      k = e + 1;
    }
    i = j + 1;
  }

  const lens = sents.map((s) => s.words);
  const mean = lens.length ? lens.reduce((a, b) => a + b, 0) / lens.length : 0;
  const sd = lens.length ? Math.sqrt(lens.reduce((a, b) => a + (b - mean) ** 2, 0) / lens.length) : 0;
  const counts = {}, inParas = {};
  for (const h of hits) { counts[h.cls] = (counts[h.cls] || 0) + 1; (inParas[h.cls] = inParas[h.cls] || new Set()).add(h.b); }
  const proseBlocks = new Set(paras.map((p) => p.b));
  const paraHits = {};
  for (const cls in inParas) paraHits[cls] = [...inParas[cls]].filter((b) => proseBlocks.has(b)).length;
  const heat = new Map();
  for (const h of hits) if (!/^sl-(noun|verb|adj|adv|conj)$/.test(h.cls)) { const s = heat.get(h.b) || new Set(); s.add(h.cls); heat.set(h.b, s); }
  for (const p of paras) p.heat = heat.has(p.b) ? heat.get(p.b).size : 0;

  const stats = {
    words, sentences: sents.length, paragraphs: paras.length,
    avgSentence: mean, variation: mean ? sd / mean : 0,
    grade: sents.length && words ? 0.39 * (words / sents.length) + 11.8 * (syl / words) - 15.59 : 0,
    minutes: words / WPM,
    adverbPct: words ? (100 * adv) / words : 0,
    passivePct: sents.length ? (100 * sents.filter((s) => s.passive).length) / sents.length : 0,
    dialogueParaPct: paras.length ? (100 * dlgParas) / paras.length : 0,
    dialogueWordPct: words ? (100 * dlgWords) / words : 0,
    longestEven, zigzags,
    pastPct: words ? (100 * past) / words : 0,
    thirdPct: words ? (100 * third) / words : 0,
    secondPct: words ? (100 * second) / words : 0,
    lumpiness: lumpiness(lens),
    pacing: dfaExponent(lens),
    mattr: mattr(allLws),
    complexPct: words ? (100 * complex) / words : 0,
    fog: sents.length && words ? 0.4 * (words / sents.length + (100 * complex) / words) : 0,
    adjPct: words ? (100 * adj) / words : 0,
    shortPct: sents.length ? (100 * sents.filter((x) => x.words <= SHORT_SENT).length) / sents.length : 0,
    paraCV: paras.length > 1 ? Math.sqrt(paras.reduce((a, p) => a + (p.words - words / paras.length) ** 2, 0) / paras.length) / (words / paras.length) : 0,
    longestPara: paras.reduce((a, p) => Math.max(a, p.words), 0),
    headingsPer1000: words ? (1000 * headings) / words : 0,
    listPer1000: words ? (1000 * lists) / words : 0,
    contractPer100: words ? (100 * contr) / words : 0,
    specificsPer100: words ? (100 * spec) / words : 0,
    openClose: (() => {
      if (paras.length < 2 || paras[0].words < 15 || paras[paras.length - 1].words < 15) return 0;
      const a0 = paras[0].stems, z = paras[paras.length - 1].stems;
      let both = 0;
      for (const x of a0) if (z.has(x)) both++;
      const un = a0.size + z.size - both;
      return un ? both / un : 0;
    })(),
  };
  const result = { hits, sents, paras, stats, counts, paraHits };
  memo = { text, result };
  return result;
}


// ---------- color fitting: keep every mark readable on the editor background ----------
const toRgb = (h) => [1, 3, 5].map((i) => parseInt(h.replace("#", "").slice(i - 1, i + 1), 16) / 255);
const lumOf = (rgb) => { const f = (c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4); return 0.2126 * f(rgb[0]) + 0.7152 * f(rgb[1]) + 0.0722 * f(rgb[2]); };
const contrastOf = (a, b) => { const x = lumOf(toRgb(a)), y = lumOf(toRgb(b)); return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05); };
function toHsl([r, g, b]) {
  const mx = Math.max(r, g, b), mn = Math.min(r, g, b), l = (mx + mn) / 2, d = mx - mn;
  if (!d) return [0, 0, l];
  const sat = l > 0.5 ? d / (2 - mx - mn) : d / (mx + mn);
  const h = mx === r ? (g - b) / d + (g < b ? 6 : 0) : mx === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return [h * 60, sat, l];
}
function fromHsl(h, sat, l) {
  const c = (1 - Math.abs(2 * l - 1)) * sat, x = c * (1 - Math.abs(((h / 60) % 2) - 1)), m = l - c / 2;
  const [r, g, b] = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  return "#" + [r + m, g + m, b + m].map((v) => Math.round(Math.max(0, Math.min(1, v)) * 255).toString(16).padStart(2, "0")).join("");
}
// Nudge a color's lightness, keeping its hue, until it reads at 4.5:1 or better on the background.
function fitColor(hex, bg, min = 4.5) {
  const [h, sat, l0] = toHsl(toRgb(hex));
  const darkBg = lumOf(toRgb(bg)) < 0.4;
  let l = l0, out = hex;
  for (let i = 0; i < 40 && contrastOf(out, bg) < min; i++) {
    l = darkBg ? Math.min(0.92, l + 0.02) : Math.max(0.08, l - 0.02);
    out = fromHsl(h, sat, l);
  }
  return out;
}
const CANVAS = { dark: "#25272b", light: "#f6f5f2" };
const INK = { dark: "#e6e8eb", light: "#1f2328" };

const refresh = StateEffect.define();
const VIEW_TYPE = "syntax-lens-panel"; // old name kept so a saved layout still finds the panel
const RULES_VERSION = 4; // bump when a rule change shifts the numbers; profiles built under an older one show a rebuild note
const MAP_TYPE = "marginalia-map";
const MAP_COLS = 90; // characters per minimap row
// [class, label, default color, hint]
// [class, label, default color, one-line help]. Labels read "Short name (detail)": the map's chips use the part before the bracket.
const ITEMS = [
  ["Syntax", [
    ["sl-noun", "Nouns and pronouns", "#4f9dde", "People, places, things, and the words that stand in for them."],
    ["sl-verb", "Verbs", "#4caf7d", "Actions and states, including helpers like is, was, will."],
    ["sl-adj", "Adjectives", "#d98cc4", "Words that describe nouns."],
    ["sl-adv", "Adverbs", "#e0913a", "Words that modify verbs or adjectives, like quickly and very."],
    ["sl-conj", "Conjunctions and prepositions", "#9aa0a6", "Connectors: and, but, because, in, of, to."],
  ]],
  ["Rhythm", [
    ["sl-long", "Long sentences (25+ words)", "#d4a017", "Past 25 words, a sentence is hard to hold in one breath. GOV.UK's plain-language ceiling."],
    ["sl-vlong", "Very long sentences (45+ words)", "#c2544d", "Past 45 words, most readers lose the thread."],
    ["sl-even", "Same-length sentences in a row (3+)", "#4f9dde", "Three or more sentences of nearly equal length read as a drone."],
    ["sl-zigzag", "Long, short, long, short (6+ sentences)", "#d98cc4", "Sentences that swing between long and short on a steady beat: a sing-song."],
    ["sl-stacc", "Run of short sentences (3+ of 5 words or fewer)", "#e0913a", "Fragment after fragment. Fine for effect, a tic when constant."],
    ["sl-opener", "Sentences starting the same way (3+ in a row)", "#e0913a", "He did this. He did that. He did the other."],
    ["sl-paraopen", "Paragraphs starting the same way (3+ in a row)", "#8a7fd1", "Back-to-back paragraphs that open on the same word."],
    ["sl-metro", "Short punch paragraphs at regular intervals", "#c2544d", "A long paragraph, a one-liner, repeat on a schedule."],
  ]],
  ["Flow", [
    ["sl-jump", "Topic jump (opens on something new)", "#4f9dde", "A sentence sharing no word with the one before it. Often fine, sometimes a dropped thread."],
    ["sl-road", "Announcing what's coming (in this post…)", "#9aa0a6", "Telling the reader the plan instead of giving them the content."],
    ["sl-throat", "Throat-clearing (it's worth noting, overall…)", "#9aa0a6", "Setup that delays the point."],
    ["sl-concede", "Concessions (that said, of course…)", "#d4a017", "Caveats scattered through a piece instead of kept in one place."],
    ["sl-tail", "Tacked-on summary ending a paragraph", "#c2544d", "A closing clause like \", reminding him that…\" that explains what the paragraph already showed."],
    ["sl-closer", "Verdict line closing a paragraph (That was the point.)", "#d4a017", "A short line announcing what the image before it already said."],
  ]],
  ["Structure", [
    ["sl-negpar", "Not X, but Y (it isn't X, it's Y)", "#c2544d", "Argues against a view nobody held. Fine once, a reflex when repeated."],
    ["sl-triplet", "Lists of three (a, b, and c)", "#8a7fd1", "Three-beat lists everywhere sound templated."],
    ["sl-which", "Trailing \", which…\" clauses", "#4caf7d", "Qualification bolted onto the end of a sentence."],
    ["sl-copdodge", "Fancy stand-ins for \"is\" (serves as, boasts)", "#d98cc4", "\"Serves as\" where \"is\" would do."],
    ["sl-rhetq", "Rhetorical questions (outside dialogue)", "#4f9dde", "Questions the writer answers right away."],
    ["sl-simile", "Similes (like a…, as if…, as X as)", "#e0913a", "Comparisons. A few good ones beat many."],
    ["sl-stack", "Stacked modifiers (2+ adverbs, 3+ adjectives)", "#d98cc4", "\"Slowly and deliberately\", \"cold, dark, empty\"."],
  ]],
  ["Words", [
    ["sl-filler", "Filler (very, really, just, a bit…)", "#8a7fd1", "Words that add nothing."],
    ["sl-wordy", "Wordy phrases (in order to, a number of)", "#c2544d", "Longer than they need to be: \"in order to\" is \"to\"."],
    ["sl-passive", "Passive voice (was eaten)", "#c2544d", "The doer is missing or pushed to the back."],
    ["sl-nom", "Abstract nouns (-tion, -ment, -ness)", "#d98cc4", "\"The implementation of\" where \"implement\" would do."],
    ["sl-vnoun", "Vague nouns (thing, aspect, factor)", "#e0913a", "Nouns that point at nothing in particular."],
    ["sl-hedge", "Hedges (perhaps, might, seems)", "#e0913a", "Words that back away from the claim."],
    ["sl-repeat", "Doubled words (the the)", "#4caf7d", "The same word twice in a row, usually a typo."],
    ["sl-radar", "Repeated word nearby (within 25 words)", "#4caf7d", "A content word recurring close by. Topic words are fine, accidents aren't."],
    ["sl-vague", "Opening on a vague it/this/that", "#4f9dde", "\"This is why…\" with no clear \"this\"."],
    ["sl-uncontr", "Uncontracted forms (do not, it is)", "#4f9dde", "Stiffer than speech, where \"don't\" and \"it's\" would sound natural."],
    ["sl-misused", "Commonly misused words (its/it's, could of)", "#e0913a", "Spelling and usage slips that spell-check misses."],
    ["sl-punct", "Em dashes and semicolons", "#d98cc4", "Marked so you can decide whether each one earns its place."],
  ]],
  ["Dialogue", [
    ["sl-dialogue", "Dialogue (quoted speech)", "#4f9dd9", "Tints everything inside quotation marks."],
    ["sl-tagfancy", "Fancy speech tags (exclaimed, retorted)", "#c2544d", "\"Said\" and \"asked\" disappear into the line. Fancy tags show."],
    ["sl-tagadv", "Adverbs in tags (said sadly)", "#e0913a", "Tells the emotion the line should carry."],
    ["sl-tagrun", "\"Said/asked\" on every line (4+ in a row)", "#9aa0a6", "Once speakers are clear, tags can drop."],
    ["sl-dlgsemi", "Semicolons inside speech", "#d98cc4", "People don't speak in semicolons."],
    ["sl-talk", "Bare dialogue with no action (6+ paragraphs)", "#8a7fd1", "Talking heads: no gesture, setting, or thought between the lines."],
  ]],
  ["Detail", [
    ["sl-spec", "Specifics (names, places, numbers)", "#4caf7d", "Not a problem flag. Shows where concrete detail lives, so thin stretches stand out."],
    ["sl-stock", "Stock body language (jaw clenched, heart raced)", "#e0913a", "Worn-out ways to show a feeling, plus body-as-observer phrasing."],
    ["sl-person", "Personified abstractions (the silence spoke)", "#d98cc4", "Abstract things doing human things, by reflex."],
    ["sl-filter", "Filter words (saw, felt, noticed)", "#4f9dde", "Narration that reports a perception instead of giving it."],
  ]],
];

const LABEL = {};
for (const [, rows] of ITEMS) for (const [cls, label] of rows) LABEL[cls] = label;
const SYNTAX = /^sl-(noun|verb|adj|adv|conj)$/;

// What covers the caret or selection: flags, sentence, paragraph.
function describeAt(a, from, to) {
  const hit = a.hits.filter((h) => (from === to ? h.from <= from && h.to >= from : h.to > from && h.from < to));
  const sent = a.sents.find((x) => x.from <= to && x.to >= from);
  const para = a.paras.find((p) => p.from <= to && p.to >= from);
  return {
    tags: [...new Set(hit.filter((h) => SYNTAX.test(h.cls)).map((h) => h.cls))],
    flags: [...new Set(hit.filter((h) => !SYNTAX.test(h.cls)).map((h) => h.cls))],
    sent, para,
  };
}

const TAB_TIPS = {
  Stats: "Numbers for this note, next to your usual range",
  Syntax: "Color words by part of speech",
  Rhythm: "Sentence and paragraph length patterns",
  Flow: "How sentences connect, and how paragraphs open and close",
  Structure: "Sentence shapes that repeat",
  Words: "Word-level habits",
  Dialogue: "Speech and speech tags (stories)",
  Detail: "Concrete detail and body-language cliches (stories)",
  Setup: "Sample folders and editor background",
  Help: "How to use Blue Pencil",
};

// Flags that only make sense for one kind of writing are hidden (and not painted) in the other mode.
const STORY_ONLY = ["sl-dialogue", "sl-tagfancy", "sl-tagadv", "sl-tagrun", "sl-dlgsemi", "sl-talk", "sl-stock", "sl-person", "sl-filter", "sl-closer"];
const ESSAY_ONLY = ["sl-throat", "sl-road", "sl-concede", "sl-nom", "sl-uncontr", "sl-jump"];
const MODE_HIDES = { story: ESSAY_ONLY, essay: STORY_ONLY };
const DEFAULT_FOLDERS = { story: "", essay: "" }; // the user points these at their own finished work in Setup
const PROFILE_STATS = ["avgSentence", "variation", "lumpiness", "pacing", "grade", "adverbPct", "passivePct", "dialogueParaPct", "dialogueWordPct", "longestEven", "pastPct", "thirdPct", "secondPct", "mattr", "fog", "complexPct", "adjPct", "shortPct", "paraCV", "longestPara", "headingsPer1000", "listPer1000", "contractPer100", "specificsPer100", "openClose"];

// Essay or story? Naive Bayes over six numbers, using the means and spreads in the two profiles.
const DETECT = ["pastPct", "thirdPct", "secondPct", "dialogueParaPct", "grade", "rate:sl-filter"];
function classify(a, profiles) {
  const w = a.stats.words;
  if (w < 150 || !profiles.essay || !profiles.story) return null;
  const vals = { pastPct: a.stats.pastPct, thirdPct: a.stats.thirdPct, secondPct: a.stats.secondPct, dialogueParaPct: a.stats.dialogueParaPct, grade: a.stats.grade, "rate:sl-filter": ((a.counts["sl-filter"] || 0) * 1000) / w };
  const ll = { essay: 0, story: 0 };
  for (const k of DETECT) for (const lab of ["essay", "story"]) {
    const m = profiles[lab].metrics[k];
    if (!m || m.sd == null) return null;
    const sd = Math.max(m.sd, 0.3);
    ll[lab] += -Math.log(sd) - (vals[k] - m.mean) ** 2 / (2 * sd * sd);
  }
  const pStory = 1 / (1 + Math.exp(-Math.max(-30, Math.min(30, ll.story - ll.essay))));
  return { label: pStory >= 0.5 ? "story" : "essay", p: Math.max(pStory, 1 - pStory) };
}
const FLAG_CLASSES = ITEMS.flatMap(([, rows]) => rows.map((r) => r[0])).filter((c) => !SYNTAX.test(c));

function quant(arr) {
  const v = [...arr].sort((a, b) => a - b);
  const q = (p) => v[Math.min(v.length - 1, Math.floor(p * v.length))];
  const mean = v.reduce((a, b) => a + b, 0) / v.length;
  const sd = Math.sqrt(v.reduce((a, b) => a + (b - mean) ** 2, 0) / v.length);
  return { p10: q(0.1), p90: q(0.9), mean, sd };
}

const fmt = (n, d = 0) => (Number.isFinite(n) ? n.toFixed(d) : "-");

class LensView extends ItemView {
  constructor(leaf, plugin) { super(leaf); this.plugin = plugin; this.rows = new Map(); this.groupOpen = {}; this.syncing = false; }
  getViewType() { return VIEW_TYPE; }
  getDisplayText() { return "Blue Pencil"; }
  getIcon() { return "highlighter"; }
  async onOpen() {
    const el = this.contentEl;
    el.empty();
    el.addClass("sl-panel");
    const names = ["Stats", ...ITEMS.map(([t]) => t), "Setup", "Help"];
    const mode = el.createDiv({ cls: "sl-mode" });
    this.modeBtns = {};
    for (const [k, l] of [["auto", "Auto"], ["essay", "Essay"], ["story", "Story"]]) {
      this.modeBtns[k] = mode.createEl("button", { text: l, cls: "sl-mode-btn" });
      this.modeBtns[k].onclick = () => this.plugin.setMode(k);
    }
    this.modeNote = el.createDiv({ cls: "sl-status sl-modenote" });
    const bar = el.createDiv({ cls: "sl-tabs" });
    this.pages = {};
    this.tabs = {};
    for (const n of names) {
      this.tabs[n] = bar.createEl("button", { text: n, cls: "sl-tab" });
      this.tabs[n].title = TAB_TIPS[n] || "";
      this.tabs[n].onclick = () => this.show(n);
      this.pages[n] = el.createDiv({ cls: "sl-page" });
    }
    this.metersEl = this.pages.Stats;
    this.toggles = new Map();
    this.pickers = new Map();
    this.masters = new Map();
    for (const [title, rows] of ITEMS) {
      const classes = rows.map((r) => r[0]);
      const master = new Setting(this.pages[title]).setName("All " + title.toLowerCase()).setClass("sl-master")
        .addToggle((t) => {
          t.setValue(classes.every((c) => this.plugin.opts.on[c]));
          t.onChange((v) => {
            const vis = classes.filter((c) => this.plugin.inMode(c));
            if (this.syncing || vis.every((c) => this.plugin.opts.on[c]) === v) return;
            this.plugin.setMany(vis, v);
            this.syncToggles();
          });
          this.masters.set(title, t);
        });
      for (const [cls, label, def, help] of rows) {
        const st = new Setting(this.pages[title]).setName(label)
          .addToggle((t) => {
            t.setValue(!!this.plugin.opts.on[cls]);
            t.onChange((v) => { if (this.syncing || !!this.plugin.opts.on[cls] === v) return; this.plugin.set(cls, v); this.syncMasters(); });
            this.toggles.set(cls, t);
          })
          .addColorPicker((c) => { this.pickers.set(cls, c); c.setValue(this.plugin.colorOf(cls)).onChange((v) => { if (this.syncing || this.plugin.colorOf(cls) === v) return; this.plugin.setColor(cls, v); }); });
        st.settingEl.title = help;
        this.rows.set(cls, st);
      }
    }
    this.buildProfileTab(this.pages.Setup);
    this.buildHelpTab(this.pages.Help);
    this.atEl = el.createDiv({ cls: "sl-at" });
    this.status = el.createEl("p", { cls: "sl-status" });
    this.showAt(this.plugin.lastAt);
    this.applyMode();
    this.show(names.includes(this.plugin.opts.tab) ? this.plugin.opts.tab : "Stats", false);
    this.plugin.refreshPanel();
  }
  showAt(info) {
    const el = this.atEl;
    el.empty();
    el.createDiv({ text: "At the cursor", cls: "sl-cap" });
    if (!info) { el.createDiv({ text: "Click a word or sentence.", cls: "sl-status" }); return; }
    const line = (cls, label, off) => {
      const d = el.createDiv({ cls: "sl-at-row" + (off ? " sl-at-off" : "") });
      const dot = d.createSpan({ cls: "sl-dot" });
      dot.style.background = this.plugin.colorOf(cls);
      d.createSpan({ text: label + (off ? " (off)" : "") });
    };
    for (const c of info.tags) line(c, LABEL[c], !this.plugin.opts.on[c]);
    const flags = info.flags.filter((c) => this.plugin.inMode(c));
    for (const c of flags) line(c, LABEL[c], !this.plugin.opts.on[c]);
    if (!flags.length) el.createDiv({ text: "No flags here.", cls: "sl-status" });
    const ctx = [];
    if (info.sent) ctx.push("Sentence: " + info.sent.words + " words");
    if (info.para) ctx.push("Paragraph: " + info.para.sents + (info.para.sents === 1 ? " sentence, " : " sentences, ") + info.para.words + " words");
    if (ctx.length) el.createDiv({ text: ctx.join(" \u00b7 "), cls: "sl-status" });
  }
  // setValue fires the change handler, so programmatic updates run under a guard.
  quiet(fn) { this.syncing = true; try { fn(); } finally { this.syncing = false; } }
  refreshColors() { this.quiet(() => { for (const [cls, c] of this.pickers) c.setValue(this.plugin.colorOf(cls)); }); }
  syncToggles() {
    this.quiet(() => { for (const [cls, t] of this.toggles) t.setValue(!!this.plugin.opts.on[cls]); });
  }
  syncMasters() {
    this.quiet(() => { for (const [title, rows] of ITEMS) this.masters.get(title).setValue(rows.filter((r) => this.plugin.inMode(r[0])).every((r) => this.plugin.opts.on[r[0]])); });
  }
  applyMode() {
    for (const k in this.modeBtns) this.modeBtns[k].toggleClass("sl-mode-on", k === this.plugin.opts.mode);
    for (const [cls, st] of this.rows) st.settingEl.toggleClass("sl-hidden", !this.plugin.inMode(cls));
    this.syncMasters();
    for (const [title, rows] of ITEMS) this.tabs[title].toggleClass("sl-hidden", !rows.some((r) => this.plugin.inMode(r[0])));
    if (this.curTab && this.tabs[this.curTab] && this.tabs[this.curTab].hasClass("sl-hidden")) this.show("Stats", false);
    const d = this.plugin.detect;
    const mode = this.plugin.opts.mode;
    this.modeNote.setText(mode !== "auto" ? "Showing the " + mode + " checks." : d ? `${d.p >= 0.95 ? "Reads like" : "Leans toward"} ${d.label === "story" ? "a story" : "an essay"}. Showing the ${this.plugin.mode()} checks.` : "Auto needs both profiles and 150+ words. Showing the " + this.plugin.mode() + " checks.");
  }
  buildProfileTab(page) {
    page.createEl("p", { cls: "sl-status", text: "A profile is your usual range for each number, measured from finished pieces. The Stats tab and the counts compare the open note against it." });
    new Setting(page).setName("Neutral editor background while marks are on")
      .setDesc("Your theme's background can hide the colors, so the editor switches to a plain dark or light neutral (following the theme) only while something is switched on.")
      .addToggle((t) => t.setValue(this.plugin.opts.bgOn).onChange(async (v) => { this.plugin.opts.bgOn = v; await this.plugin.saveData(this.plugin.opts); this.plugin.repaint(); this.plugin.applyAllColors(); }));
    for (const th of ["dark", "light"]) {
      new Setting(page).setName("Background in " + th + " themes")
        .addColorPicker((c) => c.setValue(this.plugin.opts.canvas[th] || CANVAS[th]).onChange(async (v) => {
          if ((this.plugin.opts.canvas[th] || CANVAS[th]) === v) return; this.plugin.opts.canvas[th] = v; await this.plugin.saveData(this.plugin.opts); this.plugin.applyAllColors(); }));
    }
    this.profRows = {};
    for (const [kind, label] of [["essay", "Essay"], ["story", "Story"]]) {
      this.profRows[kind] = new Setting(page).setName(label + " samples folder")
        .addText((t) => t.setPlaceholder("folder/in/vault").setValue(this.plugin.opts.folders[kind] || "")
          .onChange((v) => { this.plugin.opts.folders[kind] = v.trim(); this.plugin.saveData(this.plugin.opts); }))
        .addButton((b) => b.setButtonText("Rebuild").onClick(() => this.plugin.buildProfile(kind)));
    }
    this.profileStatus();
  }
  buildHelpTab(page) {
    const h = (t) => page.createEl("h6", { text: t, cls: "sl-helph" });
    const p = (t) => page.createEl("p", { text: t, cls: "sl-help" });
    h("Getting started");
    const ol = page.createEl("ol", { cls: "sl-help" });
    for (const t of [
      "Open a note, pick a tab, and switch something on. Marks appear in your text. Blue Pencil never changes your words.",
      "Every tab has an All switch at the top. Each row has its own color, and you can change any of them.",
      "In Setup, point Blue Pencil at folders of your finished essays and stories. It measures them once and shows your usual range for each number.",
      "Click any word to see what is flagged there. Click a bar under Stats, or anywhere on the map, to jump to that spot.",
    ]) ol.createEl("li", { text: t });
    h("Signals, not rules");
    p("One mark means almost nothing. A pattern that turns up in every paragraph is what to look at. Each row shows its hits and how many paragraphs they fall in, so you can tell a quirk from a habit. You decide what stays.");
    h("Essay or Story");
    p("Auto reads the note (past tense, he/she, dialogue, reading level) and picks. Click Essay or Story to override it. Some checks fit only one: dialogue and filter words are for stories, roadmap phrases and abstract nouns are for essays. A true story told as narrative counts as a Story.");
    h("Reading the Stats tab");
    p("The right-hand column is your usual range, the middle 80% of your own samples. \u25b2 means above it and \u25bc below. It compares you with you, not with a rulebook. Notes under about 200 words are too short to compare.");
    h("Pacing");
    p("Evenly paced prose, every stretch alike, tends to read as machine-made, and clumpy, uneven prose as human. The Pacing group measures that three ways: how much sentence length varies, how much that variation itself varies from stretch to stretch (lumpiness), and whether long and short sentences cluster or alternate (pacing memory). \"Pacing vs your usual\" averages them against your own profile. It is a weak signal on its own: it describes how a piece moves, not who wrote it.");
    h("The map");
    p("Each small bar is a word, and colored bars are flagged. The chips list what is flagged in this note: click one to see only that category, click again to go back. The shaded box is where you are scrolled. Part-of-speech colors are left off the map because they would cover everything.");
    p("The notebook icon in the ribbon shows or hides this panel and the map together.");
    h("The tabs");
    const ul = page.createEl("ul", { cls: "sl-help" });
    for (const n of Object.keys(TAB_TIPS)) ul.createEl("li", { text: n + ": " + TAB_TIPS[n] + "." });
    h("What each check means");
    for (const [title, rows] of ITEMS) {
      const det = page.createEl("details", { cls: "sl-group" });
      det.createEl("summary", { text: title });
      const list = det.createEl("ul", { cls: "sl-help" });
      for (const [, label, , help] of rows) { const li = list.createEl("li"); li.createEl("strong", { text: label + ". " }); li.appendText(help); }
    }
  }
  profileStatus() {
    for (const kind in this.profRows) {
      const p = this.plugin.profiles[kind];
      this.profRows[kind].setDesc(p ? `${p.n} pieces from ${p.folder}, built ${p.built.slice(0, 10)}` + (p.rules === RULES_VERSION ? "" : ". Built with older rules, so rebuild it.") : "No profile built yet.");
    }
  }
  show(name, save = true) {
    this.curTab = name;
    for (const n in this.pages) {
      this.pages[n].toggleClass("sl-hidden", n !== name);
      this.tabs[n].toggleClass("sl-tab-on", n === name);
    }
    if (save) { this.plugin.opts.tab = name; this.plugin.saveData(this.plugin.opts); }
  }
  render(a, md) {
    const m = this.metersEl;
    m.empty();
    if (!a) { m.createEl("p", { text: "Open a note to see its numbers.", cls: "sl-status" }); this.counts(null); return; }
    const s = a.stats;
    const paceLabel = this.paceLabel(s);
    const groups = [
      ["Size", [
        ["Words", fmt(s.words)], ["Sentences", fmt(s.sentences)], ["Paragraphs", fmt(s.paragraphs)],
        ["Reading time", fmt(s.minutes, 1) + " min"],
        ["Longest paragraph", fmt(s.longestPara) + " words", null, "longestPara", s.longestPara, 0],
      ]],
      ["Sentences", [
        ["Avg sentence", fmt(s.avgSentence, 1) + " words", null, "avgSentence", s.avgSentence, 1],
        ["Short sentences", fmt(s.shortPct, 0) + "% are 5 words or fewer", null, "shortPct", s.shortPct, 0],
        ["Longest even run", s.longestEven ? s.longestEven + " sentences" : "none", null, "longestEven", s.longestEven, 0],
        ["Long/short swings", String(s.zigzags) + (s.zigzags === 1 ? " run" : " runs")],
      ]],
      ["Pacing", [
        ["Pacing vs your usual", paceLabel, "Average of how far the four numbers below sit from your usual. Below zero means smoother and more regular than you normally write, above zero lumpier. It describes pacing, not who wrote it.", null],
        ["Length variation", fmt(s.variation, 2), "Standard deviation divided by mean sentence length. Low means even, monotone sentences.", "variation", s.variation, 2],
        ["Lumpiness", s.lumpiness == null ? "too short" : fmt(s.lumpiness, 2), "How much the variation itself varies from one stretch of ten sentences to the next. Low means every stretch is paced alike; high means calm stretches and wild ones.", "lumpiness", s.lumpiness, 2],
        ["Pacing memory", s.pacing == null ? "40+ sentences" : fmt(s.pacing, 2), "Detrended fluctuation exponent of the sentence lengths. About 0.5 is random, above 0.5 means long and short stretches cluster, below 0.5 means a steady alternation.", "pacing", s.pacing, 2],
        ["Paragraph variation", fmt(s.paraCV, 2), "Spread of paragraph lengths. Low means every paragraph is about the same size.", "paraCV", s.paraCV, 2],
      ]],
      ["Readability", [
        ["Reading grade", fmt(s.grade, 1), "Flesch-Kincaid, with an approximate syllable count.", "grade", s.grade, 1],
        ["Gunning Fog", fmt(s.fog, 1), "0.4 x (words per sentence + percent of words with 3+ syllables).", "fog", s.fog, 1],
        ["Complex words", fmt(s.complexPct, 1) + "% have 3+ syllables", null, "complexPct", s.complexPct, 1],
        ["Vocabulary diversity", fmt(s.mattr, 2), "Moving-average type-token ratio over 50-word windows. Higher means fewer repeated words.", "mattr", s.mattr, 2],
      ]],
      ["Voice", [
        ["Adverbs", fmt(s.adverbPct, 1) + "% of words", null, "adverbPct", s.adverbPct, 1],
        ["Adjectives", fmt(s.adjPct, 1) + "% of words", null, "adjPct", s.adjPct, 1],
        ["Passive", fmt(s.passivePct, 0) + "% of sentences", null, "passivePct", s.passivePct, 0],
        ["Contractions", fmt(s.contractPer100, 1) + " per 100 words", null, "contractPer100", s.contractPer100, 1],
        ["Specifics", fmt(s.specificsPer100, 1) + " per 100 words", "Names, places, acronyms, months and numerals.", "specificsPer100", s.specificsPer100, 1],
        ["Dialogue", fmt(s.dialogueParaPct, 0) + "% of paragraphs, " + fmt(s.dialogueWordPct, 0) + "% of words", null, "dialogueParaPct", s.dialogueParaPct, 0],
      ]],
      ["Shape", [
        ["Headings", fmt(s.headingsPer1000, 1) + " per 1,000 words", null, "headingsPer1000", s.headingsPer1000, 1],
        ["List items", fmt(s.listPer1000, 1) + " per 1,000 words", null, "listPer1000", s.listPer1000, 1],
        ["Closing echoes opening", fmt(s.openClose, 2), "Share of content words the last paragraph has in common with the first.", "openClose", s.openClose, 2],
      ]],
    ];
    const prof = this.plugin.profiles[this.plugin.mode()];
    const enough = s.words >= 200;
    m.createDiv({ cls: "sl-status", text: !prof ? "No " + this.plugin.mode() + " profile yet. Build one in the Setup tab to compare." : enough ? `Usual range is from your ${prof.n} ${this.plugin.mode()} pieces (middle 80%).` + (prof.rules === RULES_VERSION ? "" : " The profile was built with older rules, so rebuild it in the Setup tab.") : "Too short to compare with your usual range." });
    if (!ITEMS.some(([, rs]) => rs.some((r) => this.plugin.opts.on[r[0]] && this.plugin.inMode(r[0])))) m.createDiv({ cls: "sl-status", text: "Nothing is switched on yet. Pick a tab above and flip a toggle." });
    for (const [gname, rows] of groups) {
      const det = m.createEl("details", { cls: "sl-group" });
      det.open = this.groupOpen[gname] !== false;
      det.addEventListener("toggle", () => { this.groupOpen[gname] = det.open; });
      det.createEl("summary", { text: gname });
      const t = det.createEl("table", { cls: "sl-stats" });
      if (prof && enough && gname === "Size") { const h = t.createEl("tr", { cls: "sl-head" }); h.createEl("td"); h.createEl("td", { text: "this note" }); h.createEl("td", { text: "your usual" }); }
      for (const [k, v, tip, key, raw, d] of rows) {
        const tr = t.createEl("tr");
        const th = tr.createEl("td", { text: k, cls: "sl-k" });
        if (tip) th.title = tip;
        tr.createEl("td", { text: v });
        const u = key && enough ? this.usual(key, raw, d) : null;
        tr.createEl("td", { text: u ? u.txt : "", cls: "sl-usual" + (u ? " sl-" + u.st : "") });
      }
    }
    const jump = (from) => this.plugin.jump(md, from);
    m.createEl("div", { text: "Sentence lengths", cls: "sl-cap" });
    const ss = m.createDiv({ cls: "sl-strip" });
    let lastP = -1;
    for (const x of a.sents) {
      const cell = ss.createDiv({ cls: "sl-cell" + (x.p !== lastP && lastP !== -1 ? " sl-gap" : "") });
      lastP = x.p;
      const band = x.words >= VERY_LONG_WORDS ? "vlong" : x.words >= LONG_WORDS ? "long" : x.words <= SHORT_SENT ? "short" : "mid";
      const bar = cell.createDiv({ cls: "sl-bar sl-b-" + band });
      bar.style.height = Math.max(2, Math.min(44, x.words)) + "px";
      cell.title = x.words + " words";
      cell.onclick = () => jump(x.from);
    }
    m.createEl("div", { text: "Paragraphs (height = words, warmer = more kinds of flag)", cls: "sl-cap" });
    const ps = m.createDiv({ cls: "sl-strip sl-pstrip" });
    for (const p of a.paras) {
      const cell = ps.createDiv({ cls: "sl-cell sl-pcell" });
      const bar = cell.createDiv({ cls: "sl-bar sl-h" + Math.min(p.heat, 4) });
      bar.style.height = Math.max(2, Math.min(44, p.words / 2)) + "px";
      cell.title = p.words + " words, " + p.sents + (p.sents === 1 ? " sentence" : " sentences") + ", " + p.heat + " kinds of flag";
      cell.onclick = () => jump(p.from);
    }
    this.counts(a);
  }
  // Average z-score of the four pacing numbers against the usual profile, as a plain label.
  paceLabel(s) {
    const p = this.plugin.profiles[this.plugin.mode()];
    if (!p || s.words < 200) return "no profile yet";
    const zs = [["variation", s.variation], ["lumpiness", s.lumpiness], ["pacing", s.pacing], ["paraCV", s.paraCV]]
      .map(([k, v]) => { const m = p.metrics[k]; return m && m.sd > 0 && Number.isFinite(v) ? (v - m.mean) / m.sd : null; })
      .filter((z) => z !== null);
    if (zs.length < 2) return "too short";
    const z = meanOf(zs);
    return (z > 0 ? "+" : "") + z.toFixed(1) + (z < -0.5 ? " smoother" : z > 0.5 ? " lumpier" : " typical");
  }
  usual(key, v, d) {
    const p = this.plugin.profiles[this.plugin.mode()], m = p && p.metrics[key];
    if (!m || !Number.isFinite(v)) return null;
    const st = v < m.p10 ? "lo" : v > m.p90 ? "hi" : "ok";
    return { st, txt: `${fmt(m.p10, d)}\u2013${fmt(m.p90, d)}` + (st === "hi" ? " \u25b2" : st === "lo" ? " \u25bc" : "") };
  }
  counts(a) {
    for (const [cls, st] of this.rows) {
      if (SYNTAX.test(cls)) continue;
      if (!a) { st.setDesc(""); continue; }
      let text = `${a.counts[cls] || 0} hits, in ${a.paraHits[cls] || 0} of ${a.stats.paragraphs} paragraphs`;
      const w = a.stats.words;
      if (w >= 200) {
        const rate = ((a.counts[cls] || 0) * 1000) / w, u = this.usual("rate:" + cls, rate, 1);
        if (u) text += ` \u00b7 ${fmt(rate, 1)} per 1,000 words, usual ${u.txt}`;
      }
      st.setDesc(text);
    }
  }
}

// A minimap of the whole note: words drawn as small bars, flagged words in their category's color.
class MapView extends ItemView {
  constructor(leaf, plugin) { super(leaf); this.plugin = plugin; this.solo = null; this.rows = []; this.last = null; }
  getViewType() { return MAP_TYPE; }
  getDisplayText() { return "Blue Pencil map"; }
  getIcon() { return "map"; }
  async onOpen() {
    const el = this.contentEl;
    el.empty();
    el.addClass("sl-mapview");
    this.title = el.createDiv({ cls: "sl-maptitle" });
    this.chips = el.createDiv({ cls: "sl-chips" });
    this.msg = el.createDiv({ cls: "sl-status" });
    this.wrap = el.createDiv({ cls: "sl-mapwrap" });
    this.canvas = this.wrap.createEl("canvas", { cls: "sl-map" });
    this.vp = this.wrap.createDiv({ cls: "sl-vp" });
    this.canvas.onclick = (e) => this.click(e);
    this.ro = new ResizeObserver(() => { const w = this.wrap.clientWidth; if (this.last && w && w !== this.lastW) { this.lastW = w; this.draw(this.last.a, this.last.text, this.last.md); } });
    this.ro.observe(this.wrap);
    this.plugin.refreshPanel();
  }
  async onClose() { if (this.ro) this.ro.disconnect(); }
  // Frontmatter title, else the first H1, else the file name.
  noteTitle(file) {
    if (!file) return "No note open";
    const clean = (t) => String(t).replace(/\[\[(?:[^\]|]*\|)?([^\]]*)\]\]/g, "$1").replace(/[*_`~=]/g, "").trim();
    const cache = this.plugin.app.metadataCache.getFileCache(file);
    const fm = cache && cache.frontmatter && cache.frontmatter.title;
    if (fm && clean(fm)) return clean(fm);
    const h1 = cache && (cache.headings || []).find((h) => h.level === 1);
    if (h1 && clean(h1.heading)) return clean(h1.heading);
    return file.basename;
  }
  rowAt(y) {
    const r = this.rows;
    let lo = 0, hi = r.length - 1;
    while (lo < hi) { const mid = (lo + hi + 1) >> 1; if (r[mid].y <= y) lo = mid; else hi = mid - 1; }
    return r[lo];
  }
  click(e) {
    const row = this.rowAt(e.clientY - this.canvas.getBoundingClientRect().top);
    if (row && this.last) this.plugin.jump(this.last.md, row.from);
  }
  rowByOffset(off) {
    const r = this.rows;
    let lo = 0, hi = r.length - 1;
    while (lo < hi) { const mid = (lo + hi + 1) >> 1; if (r[mid].from <= off) lo = mid; else hi = mid - 1; }
    return r[lo];
  }
  setViewport(from, to) {
    if (!this.rows.length) { this.vp.style.display = "none"; return; }
    const t = this.rowByOffset(from), b = this.rowByOffset(to);
    this.vp.style.display = "block";
    this.vp.style.top = t.y + "px";
    this.vp.style.height = Math.max(6, b.y + b.h - t.y) + "px";
  }
  draw(a, text, md) {
    this.last = { a, text, md };
    const p = this.plugin;
    const file = md && md.file;
    this.title.setText(this.noteTitle(file));
    this.title.title = file ? file.path : "";
    const cats = FLAG_CLASSES.filter((c) => p.opts.on[c] && p.inMode(c) && a && (a.counts[c] || 0) > 0);
    this.chips.empty();
    if (!a) { this.msg.setText("Open a note to see its map."); this.canvas.style.display = "none"; this.vp.style.display = "none"; return; }
    const anyOn = FLAG_CLASSES.some((c) => p.opts.on[c] && p.inMode(c));
    this.msg.setText(cats.length || !anyOn ? "" : "Nothing in this note is flagged by what is switched on.");
    for (const c of [...cats].sort((x, y) => a.counts[y] - a.counts[x])) {
      const chip = this.chips.createDiv({ cls: "sl-chip" + (this.solo === c ? " sl-chip-on" : "") + (this.solo && this.solo !== c ? " sl-chip-dim" : "") });
      chip.createSpan({ cls: "sl-dot" }).style.background = p.colorOf(c);
      chip.createSpan({ text: LABEL[c].split(" (")[0] + " " + a.counts[c] });
      chip.onclick = () => { this.solo = this.solo === c ? null : c; this.draw(a, text, md); };
    }
    // paint[i] = which category (1-based) colors character i; the rarest category drawn last wins
    const paint = new Uint8Array(text.length);
    const order = [...cats].sort((x, y) => a.counts[y] - a.counts[x]);
    order.forEach((c, i) => {
      if (this.solo && this.solo !== c) return;
      for (const h of a.hits) if (h.cls === c) paint.fill(i + 1, h.from, Math.min(h.to, text.length));
    });
    const width = Math.max(120, this.wrap.clientWidth || 160), ppc = width / MAP_COLS;
    const [barH, rowH] = text.length < 20000 ? [3, 4] : text.length < 80000 ? [2, 3] : [1, 2];
    const gap = rowH;
    const rects = [], rows = [];
    let y = 0, off = 0;
    const fm = frontmatterEnd(text); // left off the map
    for (const line of text.split("\n")) {
      if (off < fm) { off += line.length + 1; continue; }
      if (!line.trim()) { rows.push({ y, h: gap, from: off }); y += gap; off += line.length + 1; continue; }
      let col = 0, rowFrom = off, rowY = y;
      const re = /\S+/g;
      let w;
      while ((w = re.exec(line))) {
        if (col && col + w[0].length > MAP_COLS) { rows.push({ y: rowY, h: rowH, from: rowFrom }); y += rowH; rowY = y; col = 0; rowFrom = off + w.index; }
        let k = 0;
        for (let q = off + w.index, e = q + w[0].length; q < e; q++) if (paint[q] > k) k = paint[q];
        rects.push([col * ppc, y, Math.max(1, w[0].length * ppc - 0.6), barH, k]);
        col += w[0].length + 1;
      }
      rows.push({ y: rowY, h: rowH, from: rowFrom });
      y += rowH;
      off += line.length + 1;
    }
    this.rows = rows;
    this.canvas.style.display = "block";
    this.canvas.style.width = width + "px";
    this.canvas.style.height = y + "px";
    const dpr = Math.min(window.devicePixelRatio || 1, 30000 / Math.max(1, y)); // browsers cap canvas size
    this.canvas.width = Math.round(width * dpr);
    this.canvas.height = Math.round(y * dpr);
    const ctx = this.canvas.getContext("2d");
    if (!ctx) return;
    ctx.scale(dpr, dpr);
    const base = "rgba(128,128,128,0.35)", dim = "rgba(128,128,128,0.22)";
    for (const [x, ry, rw, rh, k] of rects) {
      ctx.fillStyle = k ? p.colorOf(order[k - 1]) : this.solo ? dim : base;
      ctx.fillRect(x, ry, rw, rh);
    }
    if (p.viewRange) this.setViewport(p.viewRange.from, p.viewRange.to);
  }
}

class SyntaxLens extends Plugin {
  async onload() {
    const saved = (await this.loadData()) || {};
    this.opts = { on: saved.on || {}, colors: saved.colors || {}, tab: saved.tab, hidden: saved.hidden, mapOpened: saved.mapOpened, bgOn: saved.bgOn !== false, canvas: saved.canvas || {}, mode: saved.modeVersion === 2 ? saved.mode || "auto" : "auto", modeVersion: 2, folders: Object.assign({}, DEFAULT_FOLDERS, saved.folders) };
    this.profiles = { story: null, essay: null };
    for (const k of Object.keys(this.profiles)) {
      try {
        const p = this.manifest.dir + "/profile-" + k + ".json";
        if (await this.app.vault.adapter.exists(p)) this.profiles[k] = JSON.parse(await this.app.vault.adapter.read(p));
      } catch (e) { this.logError("profile load", e); }
    }
    this.stats = { marks: 0, error: null };
    const plugin = this;
    const marks = {};
    const mark = (cls) => (marks[cls] = marks[cls] || Decoration.mark({ class: cls }));
    this.nlp = nlpMod.exports.default || nlpMod.exports;
    const anyOn = () => Object.values(this.opts.on).some(Boolean);

    const view = ViewPlugin.fromClass(class {
      constructor(v) {
        this.v = v;
        this.decorations = this.build(v);
        this.onScroll = () => {
          if (this.raf) return;
          this.raf = requestAnimationFrame(() => {
            this.raf = 0;
            const md = plugin.md;
            if (!md || !md.editor || md.editor.cm !== v) return;
            const top = v.scrollDOM.getBoundingClientRect().top - v.documentTop;
            plugin.setViewport(v.lineBlockAtHeight(top).from, v.lineBlockAtHeight(top + v.scrollDOM.clientHeight).to);
          });
        };
        v.scrollDOM.addEventListener("scroll", this.onScroll, { passive: true });
        this.onScroll();
      }
      destroy() { this.v.scrollDOM.removeEventListener("scroll", this.onScroll); if (this.raf) cancelAnimationFrame(this.raf); }
      update(u) {
        if (u.selectionSet && !u.docChanged && plugin.app.workspace.getLeavesOfType(VIEW_TYPE).length) {
          const r = u.state.selection.main, v = u.view;
          plugin.queueAt(() => plugin.updateAt(v.state.doc.toString(), r.from, r.to));
        }
        if (u.docChanged || u.viewportChanged || u.transactions.some((t) => t.effects.some((e) => e.is(refresh))))
          this.decorations = this.build(u.view);
        if (u.docChanged || u.viewportChanged) this.onScroll();
      }
      build(v) {
        if (!anyOn()) return Decoration.none;
        try {
          const a = analyzeDoc(plugin.nlp, v.state.doc.toString()), out = [];
          for (const h of a.hits) {
            if (!plugin.opts.on[h.cls] || !plugin.inMode(h.cls)) continue;
            if (!v.visibleRanges.some((r) => h.from <= r.to && h.to >= r.from)) continue;
            out.push(mark(h.cls).range(h.from, h.to));
          }
          plugin.stats = { marks: out.length, error: null };
          plugin.setStatus();
          return Decoration.set(out, true);
        } catch (e) {
          plugin.logError("paint", e);
          plugin.stats = { marks: 0, error: String((e && e.message) || e) };
          plugin.setStatus();
          return Decoration.none;
        }
      }
    }, { decorations: (v) => v.decorations });

    this.registerEditorExtension(view);
    this.registerView(VIEW_TYPE, (leaf) => new LensView(leaf, this));
    this.registerView(MAP_TYPE, (leaf) => new MapView(leaf, this));
    this.addRibbonIcon("notebook-pen", "Blue Pencil: show or hide the panel and map", () => this.togglePanels());
    this.addCommand({ id: "toggle-panels", name: "Show or hide the panel and map", callback: () => this.togglePanels() });
    this.addCommand({ id: "open-panel", name: "Open panel", callback: () => this.openPanel() });
    this.addCommand({ id: "open-map", name: "Open map", callback: () => this.openMap() });

    this.queueAt = debounce((f) => f(), 120, true);
    this.queueRefresh = debounce(() => this.refreshPanel(), 400, true);
    this.registerEvent(this.app.workspace.on("active-leaf-change", (leaf) => {
      if (leaf && leaf.view instanceof MarkdownView) this.md = leaf.view;
      this.queueRefresh();
    }));
    this.registerEvent(this.app.workspace.on("editor-change", () => this.queueRefresh()));
    this.registerEvent(this.app.workspace.on("css-change", () => this.applyAllColors()));
    this.applyAllColors();
    this.syncCanvas();
    this.app.workspace.onLayoutReady(async () => {
      this.md = this.app.workspace.getActiveViewOfType(MarkdownView) || null;
      const ws = this.app.workspace;
      try {
        // The panel lives in the left sidebar as a tab; put it back if the layout lost it.
        if (!this.opts.hidden && !ws.getLeavesOfType(VIEW_TYPE).length) await ws.getLeftLeaf(false).setViewState({ type: VIEW_TYPE, active: false });
        // The map opens once in the right sidebar; after that it is the layout's, or the command's.
        if (!this.opts.mapOpened && !ws.getLeavesOfType(MAP_TYPE).length) {
          await ws.getRightLeaf(false).setViewState({ type: MAP_TYPE, active: false });
          this.opts.mapOpened = true;
          await this.saveData(this.opts);
        }
        this.trace("layout ready: panel leaves " + ws.getLeavesOfType(VIEW_TYPE).length + ", map leaves " + ws.getLeavesOfType(MAP_TYPE).length);
      } catch (e) { this.logError("layout ready", e); }
    });
    this.registerDomEvent(window, "error", (ev) => { if (String((ev.error && ev.error.stack) || "").includes("marginalia")) this.logError("window error", ev.error); });
    this.registerDomEvent(window, "unhandledrejection", (ev) => { if (String((ev.reason && ev.reason.stack) || "").includes("marginalia")) this.logError("unhandled rejection", ev.reason); });
    this.app.vault.adapter.stat(this.manifest.dir + "/error.log").then((st) => { if (st && st.size > 50000) return this.app.vault.adapter.write(this.manifest.dir + "/error.log", ""); }).catch(() => {}).finally(() => this.trace("loaded"));
  }
  onunload() {
    for (const d of [this.queueRefresh, this.queueAt]) if (d && d.cancel) d.cancel();
    for (const [, rows] of ITEMS) for (const [cls] of rows) document.body.style.removeProperty("--" + cls);
    document.body.classList.remove("marginalia-on");
    document.body.style.removeProperty("--sl-canvas");
    document.body.style.removeProperty("--sl-ink");
  }
  // Errors go to console and to error.log in the plugin folder, so they can be read without devtools.
  logError(where, e) {
    console.error("Blue Pencil", where, e);
    const line = `${new Date().toISOString()} ${where}: ${(e && e.stack) || e}\n`;
    this.app.vault.adapter.append(this.manifest.dir + "/error.log", line).catch(() => {});
  }
  trace(msg) { this.app.vault.adapter.append(this.manifest.dir + "/error.log", `${new Date().toISOString()} ${msg}\n`).catch(() => {}); }
  // One switch for both: if either is missing, open what is missing; if both are showing, close both.
  async togglePanels() {
    const ws = this.app.workspace;
    const havePanel = ws.getLeavesOfType(VIEW_TYPE).length > 0, haveMap = ws.getLeavesOfType(MAP_TYPE).length > 0;
    if (havePanel && haveMap) {
      ws.detachLeavesOfType(VIEW_TYPE); ws.detachLeavesOfType(MAP_TYPE);
      this.opts.hidden = true; // stays closed across restarts until toggled back on
      await this.saveData(this.opts);
      return;
    }
    this.opts.hidden = false;
    await this.saveData(this.opts);
    this.md = ws.getActiveViewOfType(MarkdownView) || this.md;
    if (!havePanel) await ws.getLeftLeaf(false).setViewState({ type: VIEW_TYPE, active: false });
    if (!haveMap) await ws.getRightLeaf(false).setViewState({ type: MAP_TYPE, active: false });
    ws.revealLeaf(ws.getLeavesOfType(VIEW_TYPE)[0]);
    ws.revealLeaf(ws.getLeavesOfType(MAP_TYPE)[0]);
    this.queueRefresh();
  }
  async openMap() {
    const { workspace } = this.app;
    this.md = workspace.getActiveViewOfType(MarkdownView) || this.md;
    let leaf = workspace.getLeavesOfType(MAP_TYPE)[0];
    if (!leaf) { leaf = workspace.getRightLeaf(false); await leaf.setViewState({ type: MAP_TYPE, active: true }); }
    workspace.revealLeaf(leaf);
  }
  setViewport(from, to) {
    this.viewRange = { from, to };
    for (const l of this.app.workspace.getLeavesOfType(MAP_TYPE)) if (l.view.setViewport) l.view.setViewport(from, to);
  }
  async openPanel() {
    const { workspace } = this.app;
    this.md = workspace.getActiveViewOfType(MarkdownView) || this.md;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE)[0];
    if (!leaf) {
      leaf = workspace.getLeftLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  mode() { return this.opts.mode === "auto" ? this.detected || "essay" : this.opts.mode; }
  inMode(cls) { return !(MODE_HIDES[this.mode()] || []).includes(cls); }
  runDetect(a) {
    const d = classify(a, this.profiles);
    const before = this.mode();
    this.detect = d;
    this.detected = d && d.p >= 0.6 ? d.label : null;
    if (this.opts.mode === "auto" && this.mode() !== before) {
      this.repaint();
    }
    for (const l of this.app.workspace.getLeavesOfType(VIEW_TYPE)) if (l.view.applyMode) l.view.applyMode();
  }
  async setMode(mode) {
    this.opts.mode = mode;
    await this.saveData(this.opts);
    for (const l of this.app.workspace.getLeavesOfType(VIEW_TYPE)) if (l.view.applyMode) l.view.applyMode();
    this.repaint();
    this.refreshPanel();
  }
  async buildProfile(kind) {
    if (this.building) return;
    this.building = true;
    try { await this.buildProfileNow(kind); } finally { this.building = false; }
  }
  async buildProfileNow(kind) {
    const folder = (this.opts.folders[kind] || "").replace(/^\/+|\/+$/g, "");
    const files = this.app.vault.getMarkdownFiles().filter((f) => folder && f.path.startsWith(folder + "/"));
    if (!files.length) { new Notice("Blue Pencil: no notes found in " + (folder || "(empty folder path)")); return; }
    const note = new Notice("Blue Pencil: profiling " + files.length + " notes...", 0);
    const rows = [];
    try {
      for (let i = 0; i < files.length; i++) {
        const a = analyzeDoc(this.nlp, await this.app.vault.cachedRead(files[i]));
        if (a.stats.words >= 300) rows.push(a);
        if (i % 5 === 0) { note.setMessage(`Blue Pencil: profiling ${i + 1}/${files.length}`); await new Promise((r) => setTimeout(r, 0)); }
      }
    } finally { note.hide(); }
    if (rows.length < 3) { new Notice("Blue Pencil: need at least 3 notes of 300+ words in " + folder + " (found " + rows.length + ")."); return; }
    const metrics = {};
    for (const k of PROFILE_STATS) metrics[k] = quant(rows.map((a) => a.stats[k]).filter((v) => Number.isFinite(v)));
    for (const c of FLAG_CLASSES) metrics["rate:" + c] = quant(rows.map((a) => ((a.counts[c] || 0) * 1000) / a.stats.words));
    const prof = { kind, folder, built: new Date().toISOString(), rules: RULES_VERSION, n: rows.length, metrics };
    await this.app.vault.adapter.write(this.manifest.dir + "/profile-" + kind + ".json", JSON.stringify(prof, null, 1));
    this.profiles[kind] = prof;
    new Notice(`Blue Pencil: ${kind} profile built from ${rows.length} pieces.`);
    for (const l of this.app.workspace.getLeavesOfType(VIEW_TYPE)) if (l.view.profileStatus) l.view.profileStatus();
    this.refreshPanel();
  }
  theme() { return document.body.classList.contains("theme-light") ? "light" : "dark"; }
  canvasColor() {
    if (!this.opts.bgOn) return this.theme() === "light" ? "#ffffff" : "#1e1e1e"; // the theme's own background, roughly
    return (this.opts.canvas || {})[this.theme()] || CANVAS[this.theme()];
  }
  colorOf(cls) {
    if (this.opts.colors[cls]) return this.opts.colors[cls];
    for (const [, rows] of ITEMS) for (const [c, , def] of rows) if (c === cls) return fitColor(def, this.canvasColor());
    return "#9aa0a6";
  }
  applyAllColors() {
    const b = document.body;
    b.style.setProperty("--sl-canvas", this.canvasColor());
    b.style.setProperty("--sl-ink", INK[this.theme()]);
    for (const [, rows] of ITEMS) for (const [cls] of rows) this.applyColor(cls, this.colorOf(cls));
    for (const l of this.app.workspace.getLeavesOfType(VIEW_TYPE)) if (l.view.refreshColors) l.view.refreshColors();
    this.queueRefresh();
  }
  // The neutral editor background only shows while at least one mark is on.
  syncCanvas() {
    const on = this.opts.bgOn && Object.keys(this.opts.on).some((c) => this.opts.on[c] && this.inMode(c));
    document.body.classList.toggle("marginalia-on", !!on);
  }
  updateAt(text, from, to) {
    try { this.lastAt = describeAt(analyzeDoc(this.nlp, text), from, to); } catch (e) { this.logError("updateAt", e); return; }
    for (const l of this.app.workspace.getLeavesOfType(VIEW_TYPE)) if (l.view.showAt) l.view.showAt(this.lastAt);
  }
  applyColor(cls, color) { document.body.style.setProperty("--" + cls, color); }
  async setColor(cls, color) { this.opts.colors[cls] = color; this.applyColor(cls, color); await this.saveData(this.opts); this.queueRefresh(); }
  async set(cls, on) {
    this.opts.on[cls] = on;
    await this.saveData(this.opts);
    this.repaint();
    this.queueRefresh();
  }
  async setMany(classes, on) {
    for (const c of classes) this.opts.on[c] = on;
    await this.saveData(this.opts);
    this.repaint();
    this.queueRefresh();
  }
  repaint() {
    this.syncCanvas();
    this.app.workspace.iterateAllLeaves((l) => {
      const cm = l.view && l.view.editor && l.view.editor.cm;
      if (cm) cm.dispatch({ effects: refresh.of(null) });
    });
  }
  jump(md, from) {
    if (!md || !md.editor) return;
    const pos = md.editor.offsetToPos(from);
    this.app.workspace.setActiveLeaf(md.leaf, { focus: true });
    md.editor.setCursor(pos);
    md.editor.scrollIntoView({ from: pos, to: pos }, true);
  }
  refreshPanel() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    const maps = this.app.workspace.getLeavesOfType(MAP_TYPE);
    if (!leaves.length && !maps.length) { // nothing to draw, but auto mode still needs the note's kind
      if (this.opts.mode === "auto" && this.md && this.md.editor) {
        try { this.runDetect(analyzeDoc(this.nlp, this.md.editor.getValue())); } catch (e) { this.logError("detect", e); }
      }
      return;
    }
    let a = null, text = "", md = this.md;
    try {
      if (md && md.editor) {
        text = md.editor.getValue();
        a = analyzeDoc(this.nlp, text);
        this.runDetect(a);
        const sel = md.editor.listSelections()[0];
        if (sel) { const p = [md.editor.posToOffset(sel.anchor), md.editor.posToOffset(sel.head)]; this.updateAt(text, Math.min(...p), Math.max(...p)); }
      }
    } catch (e) { this.logError("refresh", e); this.stats.error = String((e && e.message) || e); }
    for (const l of leaves) if (l.view.render) l.view.render(a, md);
    for (const l of maps) if (l.view.draw) l.view.draw(a, text, md);
    this.setStatus();
  }
  setStatus() {
    for (const l of this.app.workspace.getLeavesOfType(VIEW_TYPE)) {
      const el = l.view.status;
      if (el) el.setText(this.stats.error ? "Error: " + this.stats.error : `${this.stats.marks} marks in the editor`);
    }
  }
}

module.exports = SyntaxLens;
// Test hooks for the node harnesses; Obsidian ignores them.
module.exports._analyzeDoc = analyzeDoc;
module.exports._describeAt = describeAt;
module.exports._classify = classify;
module.exports._lumpiness = lumpiness;
module.exports._dfaExponent = dfaExponent;
module.exports._fitColor = fitColor; module.exports._contrastOf = contrastOf;
